#!/usr/bin/env python3

import http.server

h = http.server.SimpleHTTPRequestHandler
h.extensions_map = {
    '.html': 'text/html',
    '.wasm': 'application/wasm',
    '.js':   'application/javascript',
    '.css':  'text/css',
    '':      'text/plain',
}
httpd = http.server.HTTPServer(('127.0.0.1', 2000), h)
httpd.serve_forever()
